### ISSUE TITLE
`lang()` is deprecated

### ISSUE THREAD

**Issue by lionel-** [ColinFay/trycatchthis#16]
It has been deprecated since rlang 0.2.0 (released 4 years ago). It has been renamed to `call2()`. Please also use `!!!` instead of `splice()`.

**Comment by ColinFay** [comment]
Hey, 

I just noticed that I forgot to close this issue. 

Thanks for reporting, this has been fixed in 407a273eba72bc3170e23e1836f974db1ae3e953
